dataSource:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password:
  # the JDBC URL
  url: jdbc:mysql://127.0.0.1/aggregation_pipeline
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  # how long a connection must be held before it can be validated
  validationInterval: 10s
  # the maximum lifetime of an idle connection
  minIdleTime: 1 minute
  # the maximum lifetime of an idle connection
  maxConnectionAge: 1 minute
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

rotationManagementConfig:
  persistantFilePath: "/var/run/fk-retail-analytics/persistant_state.txt"

logging:
  appenders:
  - type : console
  - type: size-rotating-file
    logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %replace(%c: %m){'\n', '\n '}%n%replace(%ex){'(?m)^(.)',' $1'}%nopex"
    currentLogFilename: ./logs/app.log
    threshold: ALL
    archivedLogFilenamePattern: ./logs/app-%d.log.gz
    maxFileSize: "500mb"
    maxArchivedDataSize: "1gb"

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  loggers:
    "org.ehcache": DEBUG
    "org.jsr107.ri": DEBUG
    "org.hibernate": INFO
    "com.netflix": ERROR
    "com.ning": ERROR
    "org.eclipse": INFO
    "org.reflections": ERROR
    "com.sun.jersey.api": ERROR
    "org.apache.zookeeper": INFO
    "fk.sp.common.extensions.dropwizard.jersey": ERROR
    "fk.sp.sa": DEBUG

server:
  applicationConnectors:
  - type: http
    port: 18003
    acceptQueueSize: 0
  adminConnectors:
  - type: http
    port: 18004
  minThreads: 150
  maxThreads: 150
  gzip:
    enabled: true
  requestLog:
    timeZone: IST
    appenders:
    - type: console
      threshold: INFO

jerseyClient:
 timeout: 60000ms
 connectionTimeout: 20000ms
 timeToLive: 1 hour
 cookiesEnabled: true
 maxConnections: 1024
 maxConnectionsPerRoute: 1024
 keepAlive: 0s
 minThreads: 12
 maxThreads: 128
 gzipEnabled: false
 gzipEnabledForRequests: false

